org: thembaclarence
service: my-express-application

provider:
  name: aws
  runtime: nodejs10.x	
  stage: dev
  region: us-east-1

functions:
app: my-first-app
  events:
    - http: ANY /
    - http: 'ANY {proxy+}'
